// examples/vue/src/App.vue
<template>
  <div class="min-h-screen bg-white">
    <div class="max-w-6xl mx-auto p-5">
      <header class="mb-8 pb-6 border-b border-gray-200">
        <h1 class="text-2xl font-bold">
          Ustatic CSS Playground - Vue
        </h1>
        <p class="text-gray-600">
          Интерактивная демонстрация различных типов инициализации
        </p>
      </header>

      <main class="mt-8">
        <!-- Панель конфигурации -->
        <ConfigurationPanel
          @apply="handleConfigApply"
          @reset="handleConfigReset"
        />

        <!-- Код инициализации -->
        <InitCodePreview :config="currentConfig" />

        <!-- Динамическое приложение -->
        <div class="grid grid-columns--1fr-1fr gap-8 mt-6">
          <DynamicApp :config="currentConfig" />
          
          <!-- Редактор и предпросмотр HTML -->
          <div>
            <CodeEditor v-model="code" />
            <Preview :html="code" />
          </div>
        </div>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import ConfigurationPanel from './components/ConfigurationPanel.vue'
import InitCodePreview from './components/InitCodePreview.vue'
import DynamicApp from './components/DynamicApp.vue'
import CodeEditor from './components/CodeEditor.vue'
import Preview from './components/Preview.vue'

interface Config {
  type: 'modules' | 'classes'
  modules: string[]
  classesInput: string
  options: {
    loadVars: boolean
    loadBase: boolean
  }
}

// Текущая конфигурация
const currentConfig = reactive<Config>({
  type: 'modules',
  modules: [ 'flexbox', 'spacing', 'typography' ],
  classesInput: 'flex, p-4, text-lg',
  options: {
    loadVars: true,
    loadBase: true
  }
})

// Обработчики событий конфигурации
const handleConfigApply = (config: Config) => {
  Object.assign(currentConfig, config)
}

const handleConfigReset = () => {
  currentConfig.type = 'modules'
  currentConfig.modules = [ 'flexbox', 'spacing', 'typography' ]
  currentConfig.classesInput = 'flex, p-4, text-lg'
  currentConfig.options = { loadVars: true, loadBase: true }
}

// Код для редактора
const code = ref(`<div class="p-4 bg-blue-100 rounded text-center">
  <h2 class="text-xl font-bold mb-2">Пример заголовка</h2>
  <p class="text-gray-700">Это пример текста с использованием утилитарных классов</p>
  <button class="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">
    Пример кнопки
  </button>
</div>`)
</script>

// examples/svelte/src/App.svelte
<script lang="ts">
  import ModuleNavigation from './components/ModuleNavigation.svelte'
  import CodeEditor from './components/CodeEditor.svelte'
  import Preview from './components/Preview.svelte'

  // Начальный пример кода
  let code = `<div class="p-4 bg-blue-100 rounded text-center">
  <h2 class="text-xl font-bold mb-2">Пример заголовка</h2>
  <p class="text-gray-700">Это пример текста с использованием утилитарных классов</p>
  <button class="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">
    Пример кнопки
  </button>
</div>`
</script>

<div class="max-w-4xl mx-auto p-5">
  <header class="mb-8 pb-6 border-b border-gray-200">
    <h1 class="text-2xl font-bold">
      Ustatic CSS Playground
    </h1>
    <p class="text-gray-600">
      Интерактивные примеры утилитарных классов
    </p>
  </header>

  <main class="mt-8">
    <ModuleNavigation />

    <div class="grid grid-columns--1fr-1fr gap-8 mt-6">
      <CodeEditor bind:code />
      <Preview html={code} />
    </div>
  </main>
</div>
